import Head from "next/head";
import Image from "next/image";
import CallToAction from "../components/CallToAction";
import Fgl from "../components/Features";
import Footer from "../components/Footer";
import Heros from "../components/Heros";
import Navbar from "../components/Navbar";
import Preview from "../components/Preview";
import Testimonial from "../components/Testimonial";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <Navbar />
          <Heros />
        </header>
        <Preview />
        <Fgl />
        <CallToAction />
      </main>

      <footer>
        <Testimonial />
        <Footer />
      </footer>
    </>
  );
}
